\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[11pt,]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Comparing correlation coefficient methods with R : Is there really a relationship between Statistics and Timothee ?},
            pdfauthor={Thuy-My Ngo; Doriane Pfister; Léonie Lefebvre},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{longtable}
\usepackage{hologo}
\LTcapwidth=.95\textwidth
\linespread{1.05}
\usepackage{hyperref}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\title{Comparing correlation coefficient methods with R : Is there really a
relationship between Statistics and Timothee ?}
\author{Thuy-My Ngo\footnote{University of Geneva, ID 20-312-468} \and Doriane Pfister\footnote{University of Geneva, ID 20-325-122} \and Léonie Lefebvre\footnote{University of Geneva, ID 20-302-063}}
\date{May 23, 2021}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

As an apogee of the introduction to statistics course and our final
moments of being a first year undergraduate in International Relations,
this project reflects all the knowledge acquired throughout the past few
months attending this introductory class. Beginning with no history in
programming nor experience in writing a scientific report on Rmarkdown,
we were able to learn and develop step by step, our insight on the
`magic' of Data Analytics.

We are grateful to have had the chance to receive a rather large glance
at basic R commands and to put into practice the notions seen during
classe. Today, we are pleased to lead you through the outcome resulting
from our small but still progressing abilities in statistics.

\hypertarget{description-of-the-task}{%
\section{Description of the task}\label{description-of-the-task}}

In question 1 of exercise 2, our topic is related to bias study,
nonlinear relationship. We are asked to draw samples from a PDF for
(X,Y), where (X, Y) have a nonlinear relationship, using the function
gen\_nonlinear. Using the parameters assigned to us as well as an angle
parameter, we had to explain how the angle parameter visually affect the
data by comparing two scatterplots. The first generated with angle = 0,
and the second generated with angle = -0.45.

In question 2 of the same exercise, we study the Confidence Interval
Coverage. We are given the task to study the coverage of different
confidence intervals (CIs) for Px,y, with the following data settings:
1. the PDF of (X,Y) is a bivariate normal PDF 2. the PDF of (X,Y) is a
bivariate normal PDF, but the observed sample contains outliers 3. the
PDF of (X,Y) is a discrete PDF 4. X and Y have a nonlinear relationship

The types of confidence intervals used are the parametric bootstrap CI
of level = 0.8 and the non-parametric bootstrap CI of level = 0.8.

\hypertarget{motivation}{%
\section{Motivation}\label{motivation}}

We decided to take part in this scientific report as we wanted to apply
the numerous theoretical theories seen in the course provided by
Profesor Victoria-Feser. We also saw this project as an opportunity to
meet new people and experience the workgroup process, as we combine our
knowledge and perspectives on the matter, while being able to discuss
them within a group.

\hypertarget{analysis}{%
\section{Analysis}\label{analysis}}

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{RapportSTAT_files/figure-latex/nonlinear_q1-1} 

}

\caption{Hammock, this is the population correlation with angle = 0}\label{fig:nonlinear_q1}
\end{figure}

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{RapportSTAT_files/figure-latex/nonlinear_q2-1} 

}

\caption{Comet, this is the population correlation with angle = -0.45}\label{fig:nonlinear_q2}
\end{figure}

Here we see the two scatterplots of when the data is generated with
angle = 0 (Hammock), and when it is generated with angle = -0.45 (Comet)
from the samples from a PDF of (X, Y), where (X,Y) have a nonlinear
relationship.

Hammock describes a positive relationship between X and Y as the graph
shows a convex parabola (x\^{}2). As we generate the data with an angle
parameter of -0.45, we see that there is a rotation to the left. Thus,
we deduce that the angle does visually affect the data, in that it
imposes a rotation.

Furthermore, when the angle moves from \(-\pi\) to \(+\pi\), we observed
a complete rotation of the parabola.

\hypertarget{results-and-discussion-description-and-interpretation-of-the-results}{%
\section{Results and discussion: description and interpretation of the
results}\label{results-and-discussion-description-and-interpretation-of-the-results}}

\begin{table}
\centering
\begin{tabular}{l|r|>{}r|>{}r|r|>{}r}
\hline
Boot Type & Sample Size & Normal PDF & With outliers & Discrete & Non Linear\\
\hline
 & 33 & \textcolor{green}{0.771} & \textcolor{black}{0.639} & 0.776 & \textcolor{blue}{0.681}\\
\cline{2-6}
\multirow[t]{-2}{*}{\raggedright\arraybackslash Parametic} & 110 & \textcolor{green}{\textbf{0.783}} & \textcolor{orange}{0.257} & 0.776 & \textcolor{blue}{0.630}\\
\cline{1-6}
 & 33 & \textcolor{black}{0.758} & \textcolor{black}{0.758} & 0.753 & \textcolor{red}{0.725}\\
\cline{2-6}
\multirow[t]{-2}{*}{\raggedright\arraybackslash Non-Parametric} & 110 & \textcolor{black}{0.773} & \textcolor{orange}{0.431} & 0.769 & \textcolor{red}{0.723}\\
\hline
\end{tabular}
\end{table}

The following discussion will be based on the results displayed in the
Table. The use of colors to refer to the data is employed for the
reader's convenience.

We observe a decrease in the interval confidence when the parametric
boot is performed on a non-parametric functions like the discrete and
nonlinear ones (blue). Furthermore, we expect the non-parametric
bootstrap to perform better on a discrete PDF, as it is not a parametric
function.

We assumed, that the bivariate normal PDF worked the best at approaching
the confidence interval. We can see that 0.783 (bold, green) is the
closest to the 0.8, particularly when operating with the parametric boot
type.

We observe that the boot type parameter works the best when applied on a
normal PDF (green data). As the boot type parameter is based on the mean
and standard deviation, it is the most optimal approach to compute the
normal PDF's confidence interval as the latter contains these two
parameters. As for the non-parametric boot, it is the most optimal when
applied on a no parameter function like the nonlinear function. It is
displayed by the red data, which shows a greater confidence interval
than the blue data, computed with a parametric boot.

Then with the outliers setting, we see that as the n is larger, the
number of outliers increases (orange), thus making the result further
than the confidence interval. The most surprising part of the table, is
that the difference between the outliers setting when n = 33 and when n
= 110, using the parametric boot type is quite large compared to when
the data is performed with the non-parametric boot type.

\hypertarget{statistical-methods-used}{%
\section{Statistical methods used}\label{statistical-methods-used}}

The Pearson method is used to calculate a correlation coefficient that
describes the strength relationship between two variables (Kenton
(2021)), in our case X and Y, which ranges from 0 to 1. The closer the
correlation coefficient is to 0, the more the variables are independent
from each other. When equal to 1, the variables are equal to each other.
The Pearson method can be used on empirical observations in daily life
(``A Comparison of the Pearson and Spearman Correlation Methods'' 2019).
For instance, if we wanted to evaluate whether there is a positive or
negative relationship between a student's age and their level of income
when working at Starbucks.

The Spearman rank correlation method is the non-parametric version of
the Pearson correlation coefficient method (``Spearman's Rank-Order
Correlation'' 2018). It is distinct in that the Spearman correlation
coefficient is used to determine the strength of a monotonic
relationship, which is a type of function that only increases or only
decreases. In real life, we can imagine that the Spearman method would
be used to see whether an Unige exam performance in Statistics is
associated with the time students spent studying in the UniMail library.

\hypertarget{acquired-skills-during-the-term-project}{%
\section{Acquired skills during the term
project}\label{acquired-skills-during-the-term-project}}

By accomplishing this report, we had an opportunity to broaden our
understanding of the R language by computing various aspects of the
topics seen in class. Despite a short learning period time, we are now
able to compute various functions on R and interpret R codes.
Furthermore, learning to code has opened new perspectives as well as
revealed numerous ways of interpreting datasets. We will be able to
apply these perspectives to diverse daily socio-political situations.
For these reasons, the present report benefitted us greatly to acquire
skills that will make our International Relations studies more valuable.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

In conclusion, in the Nonlinear Relationship Study, we see that the
angle parameter does affect the data by imposing a rotation, moving the
parabola. As for the Confidence Interval Coverage Study, the Confidence
Interval of non-parametric boot type and of parametric boot type,
results in different outcomes depending on the setting and the sample
size. Overall, most of the outcomes are close to the confidence interval
with the highest value at 0.783 (bold, green), as one would expect.

\begin{figure}
\centering
\includegraphics[width=0.4\textwidth,height=\textheight]{cheering_minions.png}
\caption{Us three celebrating the finished report (``Giphy'' 2015)}
\end{figure}

\hypertarget{use-your-mobile-phone-to-scan-the-qr-code-below-for-a-refreshing-surprise}{%
\subsubsection{Use your mobile phone to scan the QR code below for a
refreshing
surprise!}\label{use-your-mobile-phone-to-scan-the-qr-code-below-for-a-refreshing-surprise}}

\begin{figure}
\centering
\includegraphics[width=0.1\textwidth,height=\textheight]{qrplot.png}
\caption{Surprise!}
\end{figure}

\newpage

\hypertarget{bibliography}{%
\section{Bibliography}\label{bibliography}}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-pearson_spearman_comparison}{}%
``A Comparison of the Pearson and Spearman Correlation Methods.'' 2019.
\emph{Minitab Express}.
\href{https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression\%20\%20\%20\%20\%20\%20\%20/supporting-topics/basics/a-comparison-of-the-pearson-and-spearman-correlation-methods/}{https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression       /supporting-topics/basics/a-comparison-of-the-pearson-and-spearman-correlation-methods/}.

\leavevmode\hypertarget{ref-gif_2015}{}%
``Giphy.'' 2015. giphy.com.
\url{https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif}.

\leavevmode\hypertarget{ref-kenton_2021}{}%
Kenton, Will. 2021. ``What Is the Pearson Coefficient?''
\emph{Investopedia}. Investopedia.
\url{https://www.investopedia.com/terms/p/pearsoncoefficient.asp}.

\leavevmode\hypertarget{ref-spearman_guide}{}%
``Spearman's Rank-Order Correlation.'' 2018. Lund Research Ldt.
\href{https://statistics.laerd.com/statistical-guides/spearmans-rank-order-correlation-statistical-guide\%20\%20\%20\%20\%20\%20\%20\%20\%20.php}{https://statistics.laerd.com/statistical-guides/spearmans-rank-order-correlation-statistical-guide         .php}.

\end{document}
